name: tny360
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 2090:80

networks:
  tny360:
    driver: bridge
